# Data Inspection: Lithuanian and Mexican CIS Cohorts

CIS (Clinically Isolated Syndrome) is the first neurological episode that may indicate Multiple Sclerosis - but where a formal MS diagnosis cannot yet be made.

## 1. Load Libraries and Data

Import pandas library and load both Excel files into memory as dataframes for inspection.

In [1]:
import pandas as pd

lt_df = pd.read_excel('../data/raw/lithuanian_cis.xlsx')
mx_df = pd.read_excel('../data/raw/mexican_cis.xlsx')

print('Files loaded successfully.')

Files loaded successfully.

## 2. Dataset Shapes

Shape is basically how big a dataset is - specifically, how many rows and columns. Here, pandas prints the shape of both dataframes. Each row represents a patient who presented with Clinically Isolated Syndrome (CIS), and each column represents a variable (patient information e.g. age, sex, presence of lesions in MRI).

In [2]:
print('Lithuanian CIS shape (rows, columns):', lt_df.shape)
print('Mexican CIS shape    (rows, columns):', mx_df.shape)

Lithuanian CIS shape (rows, columns): (139, 44)
Mexican CIS shape    (rows, columns): (291, 20)

## 3. Column Names

This step lists all column names for each dataset. It displays the variables in the Lithuanian study, and reveals that the Mexican dataset has a lot of unnamed columns. This could indicate blank rows above the real headers. This is checked in the next step.

In [3]:
print('=== Lithuanian CIS columns ===')
for col in lt_df.columns:
    print(' ', col)

print()
print('=== Mexican CIS columns ===')
for col in mx_df.columns:
    print(' ', col)

=== Lithuanian CIS columns ===
  Nr
  Sex
  Age
  Fatigue
  General weakness
  Pain
  Focal symptoms
  CN
  3
  4
  5
  6
  8
  Pathological reflexes
  Babinski's
  Rossolimo
  Muscle strength
  Reflex asymmetry
  Muscle tone abnormalities
  Proprioception
  Superficial sensation
  Coordination
  Balance
  Urinary incontinence
  Urine retention
  Vertigo
  Sum of symptoms
  MRI lesions specific to MS
  MRI lesions indicative of other diseases
  Unspecified MRI lesions
  MRI lesion localisation: infratentorally
  Periventricular
  Juxtacortical
  MRI spinal lesions
  Patholoigical CSF
  Increased protein
  Increased protein (g/l)
  Pleocytosis
  Pleocytosis.1
  OGB + in CSF
  IgG levels in CSF
  VEP +
  BAEP +
  MS

=== Mexican CIS columns ===
  Unnamed: 0
  Unnamed: 1
  Unnamed: 2
  Unnamed: 3
  Unnamed: 4
  Unnamed: 5
  Unnamed: 6
  Unnamed: 7
  Unnamed: 8
  Unnamed: 9
  Unnamed: 10
  Unnamed: 11
  Unnamed: 12
  Unnamed: 13
  Unnamed: 14
  Unnamed: 15
  Unnamed: 16
  Unnamed: 17
  Unnamed: 18
  Unnamed: 19

## 4. First 5 Rows

The **.head()** method pulls the first five rows of each dataset to inspect their actual values, data types, and formatting. As shown below, the Lithuanian dataset is properly structured, but the Mexican dataset reveals that the column headers actually only start on row 3.

In [4]:
print('=== Lithuanian CIS - first 5 rows ===')
display(lt_df.head())

=== Lithuanian CIS - first 5 rows ===

,Nr,Sex,Age,Fatigue,General weakness,Pain,Focal symptoms,CN,3,4,...,Patholoigical CSF,Increased protein,Increased protein (g/l),Pleocytosis,Pleocytosis.1,OGB + in CSF,IgG levels in CSF,VEP +,BAEP +,MS
0,2.0,0.0,56.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1,0,0.37,0,4,0,,0,0,0.0
1,3.0,0.0,47.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,0.28,0,0,0,22.9,0,1,0.0
2,4.0,0.0,43.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0,0,0.38,0,2,,25.3,1,0,0.0
3,5.0,0.0,39.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0,,,0,1,0,,,,0.0
4,6.0,0.0,61.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1,1,0.57,0,0,1,,1,0,0.0

Pandas uses the term **NaN** interchangeably with **null** - it stands for Not a Number and represents a missing value or empty cell. Sometimes Excel files are formatted for human reading rather than machine reading, which could explain why there are 2 rows of these in the Mexican dataset. This needs to be fixed, as **pd.read_excel()** assumes by default that the very first row contains the column headers.

In [5]:
print('=== Mexican CIS - first 5 rows ===')
display(mx_df.head())

=== Mexican CIS - first 5 rows ===

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Patient,Gender,Age (y),Schooling (y),Breastfeeding,Varicella,initial symptom,Mono or polysymptomatic,Oligoclonal bands,LLSSEP,ULSSEP,VEP,BAEP,Periventricular MRI,Cortical MRI,Infratentorial MRI,Spinal cord MRI,initial EDSS,final EDSS,group
3,1,1,34,20,1,1,2,1,0,1,1,0,0,0,1,0,1,1,1,1
4,2,1,61,25,3,2,10,2,1,1,0,1,0,0,0,0,1,2,2,1

## 5. Null Value Counts per Column

Nulls are not zero. Zero is a value, indicating something was measured and the result was zero. A null means nothing was recorded at all. Null values do not contribute meaningfully to analysis, so this step counts the missing values in each column before any analysis takes place. The output displays only columns with at least one null.

In [6]:
print('=== Lithuanian CIS - null counts per column ===')
lt_nulls = lt_df.isnull().sum()
display(lt_nulls[lt_nulls > 0].rename('null_count').to_frame() if lt_nulls.any() else 'No nulls found.')
print(f'Total nulls: {lt_nulls.sum()}')

=== Lithuanian CIS - null counts per column ===

                                          null_count
Nr                                                 1
Sex                                                1
Age                                                1
Fatigue                                            1
General weakness                                   1
Pain                                               1
Focal symptoms                                     1
CN                                                 1
3                                                  1
4                                                  1
5                                                  1
6                                                  1
8                                                  1
Pathological reflexes                              1
Babinski's                                         1
Rossolimo                                          1
Muscle strength                                    1
Reflex asymmetry                                   1
Muscle tone abnormalities                          1
Proprioception                                     1
Superficial sensation                              1
Coordination                                       1
Balance                                            1
Urinary incontinence                               1
Urine retention                                    1
Vertigo                                            1
Sum of symptoms                                    1
MRI lesion localisation: infratentorally           1
Periventricular                                    1
Juxtacortical                                      1
MRI spinal lesions                                 1
Patholoigical CSF                                  1
Increased protein                                  1
Increased protein (g/l)                           10
Pleocytosis                                        1
Pleocytosis.1                                     10
OGB + in CSF                                       2
IgG levels in CSF                                  3
VEP +                                              1
BAEP +                                             1
MS                                                 1

Total nulls: 62

In [7]:
print('=== Mexican CIS - null counts per column ===')
mx_nulls = mx_df.isnull().sum()
display(mx_nulls[mx_nulls > 0].rename('null_count').to_frame() if mx_nulls.any() else 'No nulls found.')
print(f'Total nulls: {mx_nulls.sum()}')

=== Mexican CIS - null counts per column ===

             null_count
Unnamed: 0           17
Unnamed: 1           15
Unnamed: 2           17
Unnamed: 3           18
Unnamed: 4           14
Unnamed: 5           14
Unnamed: 6            3
Unnamed: 7           14
Unnamed: 8           14
Unnamed: 9           15
Unnamed: 10          15
Unnamed: 11          15
Unnamed: 12          15
Unnamed: 13          15
Unnamed: 14          15
Unnamed: 15          15
Unnamed: 16          15
Unnamed: 17         165
Unnamed: 18         165
Unnamed: 19          15

Total nulls: 591

## Data Cleaning

This section addresses structural issues identified during inspection: blank header rows in the Mexican dataset, a ghost summary row in the Lithuanian dataset, numeric-only column names that obscure their meaning, and columns too sparse to be analytically useful.

### 6.1 Mexican Dataset: Fix Column Headers

The file loaded with `Unnamed: 0` through `Unnamed: 19` because the first row of the Excel file is blank, so pandas auto-generated column names. Reload with `header=None` to inspect the raw rows and confirm which row holds the actual column names, then reload with the correct `header` argument.

In [8]:
# Reload with no header inference to inspect the raw row structure
mx_raw = pd.read_excel('../data/raw/mexican_cis.xlsx', header=None)
print(f'Raw file shape (no header consumed): {mx_raw.shape}')
print()
print('First 5 rows (row 3 should contain the real column names):')
display(mx_raw.head(5))

Raw file shape (no header consumed): (292, 20)

First 5 rows (row 3 should contain the real column names):

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Patient,Gender,Age (y),Schooling (y),Breastfeeding,Varicella,initial symptom,Mono or polysymptomatic,Oligoclonal bands,LLSSEP,ULSSEP,VEP,BAEP,Periventricular MRI,Cortical MRI,Infratentorial MRI,Spinal cord MRI,initial EDSS,final EDSS,group
4,1,1,34,20,1,1,2,1,0,1,1,0,0,0,1,0,1,1,1,1

In [9]:
# Row 3 (0-indexed from the start of the file) contains the actual column names;
# rows 0-2 are the blank rows and old unnamed header, skipped automatically.
mx_df = pd.read_excel('../data/raw/mexican_cis.xlsx', header=3)
print('Corrected Mexican CIS column names:')
for col in mx_df.columns:
    print(' ', col)
print()
print(f'Shape after header fix: {mx_df.shape}')

Corrected Mexican CIS column names:
  Patient
  Gender
  Age (y)
  Schooling (y)
  Breastfeeding
  Varicella
  initial symptom
  Mono or polysymptomatic
  Oligoclonal bands
  LLSSEP
  ULSSEP
  VEP
  BAEP
  Periventricular MRI
  Cortical MRI
  Infratentorial MRI
  Spinal cord MRI
  initial EDSS
   final EDSS
  group

Shape after header fix: (288, 20)

### 6.2 Lithuanian Dataset: Remove Ghost Row

Inspection showed exactly 1 null in nearly every column — the signature of a single empty or summary row. The patient-ID column `Nr` is the clearest signal: any row where `Nr` is null is not a genuine patient record. Drop it and confirm the row count drops from 139 to 138.

In [10]:
ghost_mask = lt_df['Nr'].isna()
print(f'Rows with null Nr (patient ID): {ghost_mask.sum()}')
print('Ghost row:')
display(lt_df[ghost_mask])

lt_df = lt_df[~ghost_mask].reset_index(drop=True)
print(f'Row count: 139 -> {len(lt_df)}')
assert len(lt_df) == 138, 'Expected 138 rows after removing ghost row'
print('Confirmed: 138 rows.')

Rows with null Nr (patient ID): 1
Ghost row:

,Nr,Sex,Age,Fatigue,General weakness,Pain,Focal symptoms,CN,3,4,...,Patholoigical CSF,Increased protein,Increased protein (g/l),Pleocytosis,Pleocytosis.1,OGB + in CSF,IgG levels in CSF,VEP +,BAEP +,MS
138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Row count: 139 -> 138
Confirmed: 138 rows.

### 6.3 Both Datasets: Rename Numeric Columns and Drop Sparse Columns

The Lithuanian dataset has columns named `3`, `4`, `5`, `6`, `8` — these are cranial nerve assessments (CN3, CN4, CN5, CN6, CN8). Rename them to make the data self-documenting. Then, for both datasets, drop any column where more than 50% of values are null, as those columns carry too little signal to be analytically useful.

In [11]:
# Rename numeric-only cranial nerve columns in the Lithuanian dataset
lt_df = lt_df.rename(columns={'3': 'CN3', '4': 'CN4', '5': 'CN5', '6': 'CN6', '8': 'CN8'})
print('Renamed: 3->CN3, 4->CN4, 5->CN5, 6->CN6, 8->CN8')

def drop_sparse(df, threshold=0.5):
    null_frac = df.isnull().mean()
    sparse = null_frac[null_frac > threshold].index.tolist()
    if sparse:
        print(f'  Dropping {len(sparse)} column(s) with >{int(threshold * 100)}% nulls: {sparse}')
    else:
        print(f'  No columns exceed the {int(threshold * 100)}% null threshold.')
    return df.drop(columns=sparse)

print()
print('Lithuanian CIS:')
lt_df = drop_sparse(lt_df)
print(f'  Final shape: {lt_df.shape}')

print()
print('Mexican CIS:')
mx_df = drop_sparse(mx_df)
print(f'  Final shape: {mx_df.shape}')

Renamed: 3->CN3, 4->CN4, 5->CN5, 6->CN6, 8->CN8

Lithuanian CIS:
  No columns exceed the 50% null threshold.
  Final shape: (138, 44)

Mexican CIS:
  Dropping 2 column(s) with >50% nulls: ['initial EDSS', ' final EDSS']
  Final shape: (288, 18)

### 6.4 Export Cleaned Datasets

Save both cleaned DataFrames as CSV files to `data/cleaned/`. The DataFrame index is excluded since both datasets already contain patient-ID columns.

In [12]:
import os
os.makedirs('../data/cleaned', exist_ok=True)

lt_df.to_csv('../data/cleaned/lithuanian_cleaned.csv', index=False)
mx_df.to_csv('../data/cleaned/mexican_cleaned.csv', index=False)

print('Exported:')
print(f'  data/cleaned/lithuanian_cleaned.csv  -- {lt_df.shape[0]} rows x {lt_df.shape[1]} columns')
print(f'  data/cleaned/mexican_cleaned.csv     -- {mx_df.shape[0]} rows x {mx_df.shape[1]} columns')

Exported:

  data/cleaned/lithuanian_cleaned.csv  -- 138 rows x 44 columns
  data/cleaned/mexican_cleaned.csv     -- 288 rows x 18 columns