# Data Inspection: Lithuanian and Mexican CIS Cohorts

Initial exploratory data analysis to understand the structure, contents, and data quality of both datasets.

## 1. Load Libraries and Data

Import pandas and load each Excel file into its own DataFrame. Paths are relative to the project root.

In [1]:
import pandas as pd

lt_df = pd.read_excel('../data/raw/lithuanian_cis.xlsx')
mx_df = pd.read_excel('../data/raw/mexican_cis.xlsx')

print('Files loaded successfully.')

Files loaded successfully.

## 2. Dataset Shapes

Check the number of rows and columns in each dataset to get a quick sense of their size.

In [2]:
print('Lithuanian CIS shape (rows, columns):', lt_df.shape)
print('Mexican CIS shape    (rows, columns):', mx_df.shape)

Lithuanian CIS shape (rows, columns): (139, 44)
Mexican CIS shape    (rows, columns): (291, 20)

## 3. Column Names

List all column names for each dataset to understand what variables are available and identify any naming differences between cohorts.

In [3]:
print('=== Lithuanian CIS columns ===')
for col in lt_df.columns:
    print(' ', col)

print()
print('=== Mexican CIS columns ===')
for col in mx_df.columns:
    print(' ', col)

=== Lithuanian CIS columns ===
  Nr
  Sex
  Age
  Fatigue
  General weakness
  Pain
  Focal symptoms
  CN
  3
  4
  5
  6
  8
  Pathological reflexes
  Babinski's
  Rossolimo
  Muscle strength
  Reflex asymmetry
  Muscle tone abnormalities
  Proprioception
  Superficial sensation
  Coordination
  Balance
  Urinary incontinence
  Urine retention
  Vertigo
  Sum of symptoms
  MRI lesions specific to MS
  MRI lesions indicative of other diseases
  Unspecified MRI lesions
  MRI lesion localisation: infratentorally
  Periventricular
  Juxtacortical
  MRI spinal lesions
  Patholoigical CSF
  Increased protein
  Increased protein (g/l)
  Pleocytosis
  Pleocytosis.1
  OGB + in CSF
  IgG levels in CSF
  VEP +
  BAEP +
  MS

=== Mexican CIS columns ===
  Unnamed: 0
  Unnamed: 1
  Unnamed: 2
  Unnamed: 3
  Unnamed: 4
  Unnamed: 5
  Unnamed: 6
  Unnamed: 7
  Unnamed: 8
  Unnamed: 9
  Unnamed: 10
  Unnamed: 11
  Unnamed: 12
  Unnamed: 13
  Unnamed: 14
  Unnamed: 15
  Unnamed: 16
  Unnamed: 17
  Unnamed: 18
  Unnamed: 19

## 4. First 5 Rows

Preview the first five rows of each dataset to inspect actual values, data types, and formatting.

In [4]:
print('=== Lithuanian CIS — first 5 rows ===')
display(lt_df.head())

=== Lithuanian CIS — first 5 rows ===

,Nr,Sex,Age,Fatigue,General weakness,Pain,Focal symptoms,CN,3,4,...,Patholoigical CSF,Increased protein,Increased protein (g/l),Pleocytosis,Pleocytosis.1,OGB + in CSF,IgG levels in CSF,VEP +,BAEP +,MS
0,2.0,0.0,56.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1,0,0.37,0,4,0,,0,0,0.0
1,3.0,0.0,47.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,0.28,0,0,0,22.9,0,1,0.0
2,4.0,0.0,43.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0,0,0.38,0,2,,25.3,1,0,0.0
3,5.0,0.0,39.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0,,,0,1,0,,,,0.0
4,6.0,0.0,61.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1,1,0.57,0,0,1,,1,0,0.0

In [5]:
print('=== Mexican CIS — first 5 rows ===')
display(mx_df.head())

=== Mexican CIS — first 5 rows ===

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Patient,Gender,Age (y),Schooling (y),Breastfeeding,Varicella,initial symptom,Mono or polysymptomatic,Oligoclonal bands,LLSSEP,ULSSEP,VEP,BAEP,Periventricular MRI,Cortical MRI,Infratentorial MRI,Spinal cord MRI,initial EDSS,final EDSS,group
3,1,1,34,20,1,1,2,1,0,1,1,0,0,0,1,0,1,1,1,1
4,2,1,61,25,3,2,10,2,1,1,0,1,0,0,0,0,1,2,2,1

## 5. Null Value Counts per Column

Count missing values in each column to identify data quality issues before any analysis. Only columns with at least one null are shown to keep the output readable.

In [6]:
print('=== Lithuanian CIS — null counts per column ===')
lt_nulls = lt_df.isnull().sum()
display(lt_nulls[lt_nulls > 0].rename('null_count').to_frame() if lt_nulls.any() else 'No nulls found.')
print(f'Total nulls: {lt_nulls.sum()}')

=== Lithuanian CIS — null counts per column ===

                                          null_count
Nr                                                 1
Sex                                                1
Age                                                1
Fatigue                                            1
General weakness                                   1
Pain                                               1
Focal symptoms                                     1
CN                                                 1
3                                                  1
4                                                  1
5                                                  1
6                                                  1
8                                                  1
Pathological reflexes                              1
Babinski's                                         1
Rossolimo                                          1
Muscle strength                                    1
Reflex asymmetry                                   1
Muscle tone abnormalities                          1
Proprioception                                     1
Superficial sensation                              1
Coordination                                       1
Balance                                            1
Urinary incontinence                               1
Urine retention                                    1
Vertigo                                            1
Sum of symptoms                                    1
MRI lesion localisation: infratentorally           1
Periventricular                                    1
Juxtacortical                                      1
MRI spinal lesions                                 1
Patholoigical CSF                                  1
Increased protein                                  1
Increased protein (g/l)                           10
Pleocytosis                                        1
Pleocytosis.1                                     10
OGB + in CSF                                       2
IgG levels in CSF                                  3
VEP +                                              1
BAEP +                                             1
MS                                                 1

Total nulls: 62

In [7]:
print('=== Mexican CIS — null counts per column ===')
mx_nulls = mx_df.isnull().sum()
display(mx_nulls[mx_nulls > 0].rename('null_count').to_frame() if mx_nulls.any() else 'No nulls found.')
print(f'Total nulls: {mx_nulls.sum()}')

=== Mexican CIS — null counts per column ===

             null_count
Unnamed: 0           17
Unnamed: 1           15
Unnamed: 2           17
Unnamed: 3           18
Unnamed: 4           14
Unnamed: 5           14
Unnamed: 6            3
Unnamed: 7           14
Unnamed: 8           14
Unnamed: 9           15
Unnamed: 10          15
Unnamed: 11          15
Unnamed: 12          15
Unnamed: 13          15
Unnamed: 14          15
Unnamed: 15          15
Unnamed: 16          15
Unnamed: 17         165
Unnamed: 18         165
Unnamed: 19          15

Total nulls: 591